name: Build and Push ARM Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms:  linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: gunamadura/myoctopus:latest
      - name: Verify Docker Image
        run: |
          docker run --rm gunamadura/myoctopus:latest uname -m
      - name: check Docker Status
        run:
          docker info
      - name: Pull Docker Image
        run: docker pull gunamadura/myoctopus:latest
      - name: List Images
        run: docker images
      